try to use cibuildwheel from console

diff --git a/.github/workflows/test_windows.yaml b/.github/workflows/test_windows.yaml
--- a/.github/workflows/test_windows.yaml
+++ b/.github/workflows/test_windows.yaml
@@ -43,42 +43,51 @@ jobs:
           mkdir -p ${GITHUB_WORKSPACE}/pyproj/proj_dir/share/proj
           ls "$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}/"*
           cp "$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}/share/proj/"* ${GITHUB_WORKSPACE}/pyproj/proj_dir/share/proj/
-
+      - name: Install build dependencies
+        run: |
+          python -m pip install pybind11 cibuildwheel delvewheel
       - name: Build wheels
-        uses: pypa/cibuildwheel@v2.16
-        env:
-          CIBW_SKIP: "*musllinux* pp*-win* pp31*"
-          CIBW_ARCHS: ${{ matrix.arch }}
-            #CIBW_BEFORE_ALL: >
-            #  git clone https://github.com/pyproj4/pyproj.git
-            #  cd pyproj
-            #  git checkout ${PYPROJ_VERSION}
-          CIBW_ENVIRONMENT_WINDOWS:
-            PROJ_WHEEL=true
-            PROJ_NETWORK=ON
-            PROJ_VERSION=${{ env.PROJ_VERSION }}
-            PROJ_DIR=$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}
-          CIBW_BEFORE_BUILD_WINDOWS: >
-            git clone https://github.com/pyproj4/pyproj.git
-            cd pyproj
-            git checkout ${PYPROJ_VERSION}
-            python -m pip install delvewheel
-          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:/vcpkg/installed/${{ matrix.triplet }}/bin -w {dest_dir} {wheel}"
-          CIBW_TEST_REQUIRES: cython pytest numpy --config-settings=setup-args="-Dallow-noblas=true"
-          CIBW_BEFORE_TEST: python -m pip install shapely pandas xarray || echo "Optional requirements install failed"
-          CIBW_TEST_COMMAND: >
-            pyproj -v &&
-            python -c "import pyproj; pyproj.Proj(init='epsg:4269')"  &&
-            cp -r {package}/test . &&
-            python -m pytest test -v -s
-        with:
-          package-dir: pyproj
+        shell: bash
+        # uses: pypa/cibuildwheel@v2.8.1
+        run: |
+          git clone https://github.com/pyproj4/pyproj.git
+          cd pyproj
+          git checkout ${PYPROJ_VERSION}
+          cibuildwheel
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v3
         with:
           path: ./wheelhouse/*.whl
           retention-days: 5
+#
+          #- name: Build wheels
+          #  uses: pypa/cibuildwheel@v2.16
+          #  env:
+          #    CIBW_SKIP: "*musllinux* pp*-win* pp31*"
+          #    CIBW_ARCHS: ${{ matrix.arch }}
+          #    CIBW_BEFORE_ALL: >
+          #      git clone https://github.com/pyproj4/pyproj.git
+          #      cd pyproj
+          #      git checkout ${PYPROJ_VERSION}
+          #    CIBW_ENVIRONMENT_WINDOWS:
+          #      PROJ_WHEEL=true
+          #      PROJ_NETWORK=ON
+          #      PROJ_VERSION=${{ env.PROJ_VERSION }}
+          #      PROJ_DIR=$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}
+          #    CIBW_BEFORE_BUILD_WINDOWS: >
+          #      python -m pip install delvewheel
+          #    CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:/vcpkg/installed/${{ matrix.triplet }}/bin -w {dest_dir} {wheel}"
+          #    CIBW_TEST_REQUIRES: cython pytest numpy --config-settings=setup-args="-Dallow-noblas=true"
+          #    CIBW_BEFORE_TEST: python -m pip install shapely pandas xarray || echo "Optional requirements install failed"
+          #    CIBW_TEST_COMMAND: >
+          #      pyproj -v &&
+          #      python -c "import pyproj; pyproj.Proj(init='epsg:4269')"  &&
+          #      cp -r {package}/test . &&
+          #      python -m pytest test -v -s
+          #  with:
+          #    package-dir: pyproj
+
 
   build_GDAL:
     name: GDAL ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.triplet }}
@@ -120,20 +129,23 @@ jobs:
           cp "$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}/share/proj/"* ${GITHUB_WORKSPACE}/pyproj/proj_dir/share/proj/
           pip download GDAL==${GDAL_VERSION}
           ls GDAL-${GDAL_VERSION}.tar.gz
-          tar xzvf GDAL-${GDAL_VERSION}.tar.gz                                    
-          cd GDAL-${GDAL_VERSION}
+          tar xzvf GDAL-${GDAL_VERSION}.tar.gz
+          mv GDAL-${GDAL_VERSION} gdal
+          ls
 
       - name: Build wheels
         uses: pypa/cibuildwheel@v2.16
         env:
           CIBW_SKIP: "*musllinux* pp*-win* pp31*"
           CIBW_ARCHS: ${{ matrix.arch }}
-          CIBW_ENVIRONMENT_WINDOWS:
-            PROJ_WHEEL=true
-            PROJ_NETWORK=ON
-            PROJ_VERSION=${{ env.PROJ_VERSION }}
-            PROJ_DIR=$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}
-          CIBW_BEFORE_BUILD_WINDOWS: "python -m pip install delvewheel numpy"
+            #CIBW_ENVIRONMENT_WINDOWS:
+            #  PROJ_WHEEL=true
+            #  PROJ_NETWORK=ON
+            #  PROJ_VERSION=${{ env.PROJ_VERSION }}
+            #  PROJ_DIR=$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}
+            #CIBW_BEFORE_BUILD_WINDOWS: "python -m pip install delvewheel numpy"
           CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:/vcpkg/installed/${{ matrix.triplet }}/bin -w {dest_dir} {wheel}"
           CIBW_TEST_REQUIRES: cython pytest numpy --config-settings=setup-args="-Dallow-noblas=true"
           CIBW_BEFORE_TEST: python -m pip install shapely pandas xarray || echo "Optional requirements install failed"
+        with:
+          package-dir: pyproj
