try to use cibuildwheel with env of action

diff --git a/.github/workflows/test_windows.yaml b/.github/workflows/test_windows.yaml
--- a/.github/workflows/test_windows.yaml
+++ b/.github/workflows/test_windows.yaml
@@ -40,19 +40,37 @@ jobs:
           cp ${GITHUB_WORKSPACE}/windows/vcpkg_proj.json ${GITHUB_WORKSPACE}/windows/vcpkg.json
           cat ${GITHUB_WORKSPACE}/windows/vcpkg.json
           vcpkg install --feature-flags="versions,manifests" --x-manifest-root=${GITHUB_WORKSPACE}/windows --x-install-root=$VCPKG_INSTALLATION_ROOT/installed
-          mkdir -p ${GITHUB_WORKSPACE}/pyproj/proj_dir/share/proj
-          ls "$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}/"*
-          cp "$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}/share/proj/"* ${GITHUB_WORKSPACE}/pyproj/proj_dir/share/proj/
-      - name: Install build dependencies
-        run: |
-          python -m pip install pybind11 cibuildwheel delvewheel
-      - name: Build wheels
-        shell: bash
-        # uses: pypa/cibuildwheel@v2.8.1
-        run: |
           git clone https://github.com/pyproj4/pyproj.git
           cd pyproj
           git checkout ${PYPROJ_VERSION}
+          mkdir -p ${GITHUB_WORKSPACE}/pyproj/proj_dir/share/proj
+          ls "$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}/"*
+          cp "$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}/share/proj/"* ${GITHUB_WORKSPACE}/pyproj/proj_dir/share/proj/
+
+#
+      - name: Build wheels
+        env:
+          CIBW_SKIP: "*musllinux* pp*-win* pp31*"
+          CIBW_ARCHS: ${{ matrix.arch }}
+          CIBW_ENVIRONMENT_WINDOWS:
+            PROJ_WHEEL=true
+            PROJ_NETWORK=ON
+            PROJ_VERSION=${{ env.PROJ_VERSION }}
+            PROJ_DIR=$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}
+          CIBW_BEFORE_BUILD_WINDOWS: >
+            python -m pip install delvewheel
+          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:/vcpkg/installed/${{ matrix.triplet }}/bin -w {dest_dir} {wheel}"
+          CIBW_TEST_REQUIRES: cython pytest numpy --config-settings=setup-args="-Dallow-noblas=true"
+          CIBW_BEFORE_TEST: python -m pip install shapely pandas xarray || echo "Optional requirements install failed"
+          CIBW_TEST_COMMAND: >
+            pyproj -v &&
+            python -c "import pyproj; pyproj.Proj(init='epsg:4269')"  &&
+            cp -r {package}/test . &&
+            python -m pytest test -v -s
+        run: |
+          pwd
+          ls
+          python -m pip install pybind11 cibuildwheel==2.16.2 delvewheel
           cibuildwheel
 
       - name: Upload artifacts
@@ -60,34 +78,6 @@ jobs:
         with:
           path: ./wheelhouse/*.whl
           retention-days: 5
-#
-          #- name: Build wheels
-          #  uses: pypa/cibuildwheel@v2.16
-          #  env:
-          #    CIBW_SKIP: "*musllinux* pp*-win* pp31*"
-          #    CIBW_ARCHS: ${{ matrix.arch }}
-          #    CIBW_BEFORE_ALL: >
-          #      git clone https://github.com/pyproj4/pyproj.git
-          #      cd pyproj
-          #      git checkout ${PYPROJ_VERSION}
-          #    CIBW_ENVIRONMENT_WINDOWS:
-          #      PROJ_WHEEL=true
-          #      PROJ_NETWORK=ON
-          #      PROJ_VERSION=${{ env.PROJ_VERSION }}
-          #      PROJ_DIR=$VCPKG_INSTALLATION_ROOT/installed/${{ matrix.triplet }}
-          #    CIBW_BEFORE_BUILD_WINDOWS: >
-          #      python -m pip install delvewheel
-          #    CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:/vcpkg/installed/${{ matrix.triplet }}/bin -w {dest_dir} {wheel}"
-          #    CIBW_TEST_REQUIRES: cython pytest numpy --config-settings=setup-args="-Dallow-noblas=true"
-          #    CIBW_BEFORE_TEST: python -m pip install shapely pandas xarray || echo "Optional requirements install failed"
-          #    CIBW_TEST_COMMAND: >
-          #      pyproj -v &&
-          #      python -c "import pyproj; pyproj.Proj(init='epsg:4269')"  &&
-          #      cp -r {package}/test . &&
-          #      python -m pytest test -v -s
-          #  with:
-          #    package-dir: pyproj
-
 
   build_GDAL:
     name: GDAL ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.triplet }}
